services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
      - "19092:19092"

  
  create-topic:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_create_topic
    depends_on:
      - kafka

    command: bash -c "
      echo '⏳ Waiting for Kafka...' &&
      cub kafka-ready -b kafka:9092 1 30 &&
      kafka-topics --create --if-not-exists --topic transactions --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 &&
      echo '✅ Topic created!'
      "
    networks:
      - kafka-net


  debug-container:
    image: python:3.12-slim
    container_name: debug-container
    working_dir: /app
    volumes:
      - ./../streaming:/app/streaming
      - ./../features:/app/features
    tty: true        # Keep container alive
    stdin_open: true # Allow interactive mode
    command: bash -c "pip install kafka-python && bash"
    networks:
      - kafka-net


networks:
  kafka-net:
    driver: bridge
