services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    ports:
      - "9092:9092"

  create-topic:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [kafka]
    entrypoint: >
      bash -c "sleep 5 &&
      kafka-topics --create --topic tx_stream
        --bootstrap-server kafka:9092
        --partitions 3
        --replication-factor 1
        --if-not-exists"
    restart: "no"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  producer:
    build:
      context: ..
      dockerfile: infra/Dockerfile.producer
    depends_on: [create-topic]
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092

  consumer:
    build:
      context: ..
      dockerfile: infra/Dockerfile.consumer
    depends_on: [create-topic, postgres]
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    depends_on: [consumer]
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "8000:8000"
